### ISSUE TITLE
회원가입 기능

### ISSUE THREAD

**Issue by secondJW** [atimevil/ICY#5]
## 💡기능 구현 설명💡
- 기능 설명
이슈 이름이 회원가입 기능이지만 회원 탈퇴까지 구현 했습니다

## To-Do
- [x] 사용자 아이디 유효성 검사 -회원가입
- [x] 사용자 비밀번호 유효성 검사 -회원가입
- [x] 사용자 아이디/비밀번호 예외처리 -회원가입
- [x] 사용자 아이디/비밀번호 예외처리 -회원탈퇴
- [x] 사용자 정의 예외 만들어서 처리
